networks:
  dev:
    driver: bridge

services:
  twitterapi:
    image: twitterapi
    depends_on: 
      - "app_db"
    ports:
      - "127.0.0.1:4000:80"
    build:
      context: .
      dockerfile: TwitterAPI/Dockerfile
    env_file:
      - .env
    environment:
      - ConnectionStrings__WebApiDatabase=${DBCONNECTIONSTRING}
      - ASPNETCORE_URLS=${ASPNETCOREURLS}
      - KeyVaultConfiguration__Vault=${VAULTURI}
      - KeyVaultConfiguration__TenantId=${TENANTID}
      - KeyVaultConfiguration__ClientId=${CLIENTID}
      - KeyVaultConfiguration__ClientSecret=${CLIENTSECRET}
      - Jwt__Secret=${JWTSECRET}
    networks:
      - dev
        
  app_db:
    image: postgres:latest
    container_name: app_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=TwitterDB
    ports:
      - "127.0.0.1:5434:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  app_data: