networks:
  dev:
    driver: bridge

services:
  twitterapi:
    image: twitterapi
    depends_on: 
      - "app_db"
    ports:
      - "4000:80"
    build:
      context: .
      dockerfile: TwitterAPI/Dockerfile
    environment:
      - ConnectionStrings__WebApiDatabase=User ID=postgres;Password=postgres;Host=app_db;Server=app_db;Port=5432;Database=TwitterDB;Integrated Security=true;Pooling=true;
      - ASPNETCORE_URLS=http://+:80
      - PasswordHashPepper=12345678901234567890123456789012
      - Jwt__Secret=This is the secure key for the JWT token.
    networks:
      - dev
        
  app_db:
    image: postgres:latest
    container_name: app_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=TwitterDB
    ports:
      - "5434:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  app_data: